import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Initialize theme early to avoid flash of incorrect theme */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
  try {
    const pref = localStorage.getItem('pref_theme');
    const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    const shouldDark = pref === 'dark' || (pref !== 'light' && systemDark);
    const root = document.documentElement;
                    if (shouldDark) {
                      root.classList.add('dark');
                    } else {
                      root.classList.remove('dark');
                    }
                    root.classList.add('theme-transition');
  } catch (_) {}
})();`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
